
#Sort interesting variables and make a data set with strength change variabl
brukes i den tabbel 3 mot 1.

```{r}
#| label:styrke
#| echo:false
#| fig-cap:"test"
#| echo:fals
#| warning:fals
#| message:false
str.dat <- strengthvolume %>%
  filter(!is.na(load)) %>%
  group_by(exercise) %>%
  mutate(scaled.load = load / max(load, na.rm = TRUE)) %>%
  group_by(participant, time, sex, sets) %>%
  summarise(combined.load = mean(scaled.load, na.rm = TRUE)) %>%
  ungroup() %>%
  pivot_wider(names_from = time,
              values_from = combined.load) %>%
  mutate(change_perc = ((post - pre) / pre) * 100) 
  
```


Tabell 3: Gjennomsnittlig forandring i styrke fr책 3 til 1 set


```{r}
#| label:styrke
#| echo:false
#| fig-cap:"test 2"
#| echo:false
#| warning:fals
#| message:false
str.dat %>%    
  filter(!is.na(post)) %>%
  group_by(sets) %>%
  summarise(m = mean(change_perc),
            sd = sd(change_perc)) %>%
  mutate(sets = factor(sets, levels = c("multiple", "single"),
                       labels = c("3 sets", "1 sets"))) %>%
  mutate(ms = paste0(signif(m, 3), "(", signif(sd, 3), ")")) %>%
  gt() %>% 
  tab_header(
    title = "Tabell 3: Gjennomsnittlig forandring i styrke fr책 3 til 1 set",
    subtitle = "M책lt i prosent") %>% 
  fmt_number(columns = c(m, sd), decimals = 0) %>% 
  fmt_percent(columns = c(m, sd), decimals = 2) %>% 
  cols_label(sets = "Set", ms = "% forandring(SD)") %>% 
  cols_hide(columns = c(m, sd)) %>% 
  tab_footnote("Gjennomsnitlig forandring i % (SD for 3 sets og 1 set).")
```
  
  Anova

```{r}
#| echo: false
#| warning: false
#| message: false

m2 <- lm(post ~ pre + sets, data = str.dat)

summary(m2)
plot(m2)
```
  
```{r}
#| echo: false
#| warning: false
#| message: false

str.mod <- strengthvolume %>%
  group_by(exercise) %>%
  mutate(scaled.load =load/max(load,na.rm = TRUE)) %>%
  group_by(participant, time, sex, sets) %>%
  summarise(combined.load = mean(scaled.load, na.rm = TRUE)) %>%
  ungroup()

str.mod %>%
  filter(!is.na(combined.load), time == factor(time, levels = c("pre", "post"))) %>%
  mutate(time = factor(time, levels = c("pre", "post")),
         group = factor(sets, levels = c("Single", "Multiple"))) %>%
 ggplot(aes(time, combined.load, group = paste(participant, sets), color = sets)) + geom_line() + theme_bw() + labs(title = "Tabell 4: Forandring i styrke",
       y = "Forandring i styrke (kombinert belastning)",
       x = "Tid",
       caption = "Tabell 4: Viser forskjellen mellom multiple and single set p책 styrke forandring.")
```
                            
```
  
  